INSERT INTO AUTHOR(FIRST_NAME,LAST_NAME,EMAIL,MOBILE_NUMBER) VALUES('Yashavant','Kanetkar','yk@example.com','12345679');
INSERT INTO AUTHOR(FIRST_NAME,LAST_NAME,EMAIL,MOBILE_NUMBER) VALUES('Balguruswamy','E','be@example.com','1234568');
INSERT INTO AUTHOR(FIRST_NAME,LAST_NAME,EMAIL,MOBILE_NUMBER) VALUES('Chetan','Bhagat','cb@example.com','1234569');
